'use client'
import { ArrowLeft } from 'lucide-react'

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white shadow-sm">
        <div className="container mx-auto px-4 py-6">
          <div className="flex justify-between items-center">
            <h1 className="text-2xl font-bold text-gray-900">Privacy Policy</h1>
            <a 
              href="/" 
              className="text-primary-600 hover:text-primary-700 font-medium flex items-center"
            >
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to App
            </a>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <div className="bg-white rounded-lg shadow-sm p-8">
          <div className="mb-8">
            <p className="text-sm text-gray-600 mb-4">
              <strong>Last updated:</strong> {new Date().toLocaleDateString()}
            </p>
            <p className="text-gray-700">
              At AI Meeting Summarizer, we are committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our AI-powered meeting summarization service.
            </p>
          </div>

          <div className="space-y-8">
            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">1. Information We Collect</h2>
              
              <h3 className="text-xl font-semibold text-gray-900 mb-3">1.1 Personal Information</h3>
              <ul className="list-disc list-inside text-gray-700 space-y-2 mb-4">
                <li>Email address (when you contact us for support)</li>
                <li>Payment information (processed securely through PayHere)</li>
                <li>Usage patterns and preferences</li>
              </ul>

              <h3 className="text-xl font-semibold text-gray-900 mb-3">1.2 Meeting Data</h3>
              <ul className="list-disc list-inside text-gray-700 space-y-2 mb-4">
                <li>Meeting transcripts that you upload or input</li>
                <li>Meeting summaries generated by our AI</li>
                <li>Meeting metadata (duration, participants, etc.)</li>
              </ul>

              <h3 className="text-xl font-semibold text-gray-900 mb-3">1.3 Technical Information</h3>
              <ul className="list-disc list-inside text-gray-700 space-y-2">
                <li>IP address and browser information</li>
                <li>Device information and operating system</li>
                <li>Usage analytics and performance data</li>
                <li>Cookies and similar tracking technologies</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">2. How We Use Your Information</h2>
              <ul className="list-disc list-inside text-gray-700 space-y-2">
                <li>To provide and improve our AI meeting summarization service</li>
                <li>To process payments and manage your subscription</li>
                <li>To communicate with you about your account and our services</li>
                <li>To provide customer support and respond to inquiries</li>
                <li>To analyze usage patterns and improve our AI models</li>
                <li>To ensure the security and integrity of our platform</li>
                <li>To comply with legal obligations and protect our rights</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">3. AI Processing and Data Security</h2>
              <div className="text-gray-700 space-y-3">
                <p>
                  <strong>AI Processing:</strong> Your meeting transcripts are processed by our AI systems to generate summaries. This processing is done securely and is essential for providing our service.
                </p>
                <p>
                  <strong>Data Retention:</strong> Meeting transcripts and summaries are stored securely and are only retained for as long as necessary to provide our service or as required by law.
                </p>
                <p>
                  <strong>Security Measures:</strong> We implement industry-standard security measures including encryption, secure servers, and access controls to protect your data.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">4. Information Sharing and Disclosure</h2>
              <p className="text-gray-700 mb-3">
                We do not sell, trade, or rent your personal information to third parties. We may share your information only in the following circumstances:
              </p>
              <ul className="list-disc list-inside text-gray-700 space-y-2">
                <li>With payment processors (PayHere) to process transactions</li>
                <li>With AI service providers that help us deliver our core functionality</li>
                <li>When required by law or to protect our legal rights</li>
                <li>In connection with a business transfer or merger</li>
                <li>With your explicit consent</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Cookies and Tracking Technologies</h2>
              <p className="text-gray-700 mb-3">
                We use cookies and similar technologies to:
              </p>
              <ul className="list-disc list-inside text-gray-700 space-y-2">
                <li>Remember your preferences and settings</li>
                <li>Analyze how you use our service</li>
                <li>Improve our website functionality</li>
                <li>Provide personalized experiences</li>
              </ul>
              <p className="text-gray-700 mt-3">
                You can control cookies through your browser settings, but disabling cookies may affect the functionality of our service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">6. Your Rights and Choices</h2>
              <p className="text-gray-700 mb-3">
                You have the following rights regarding your personal information:
              </p>
              <ul className="list-disc list-inside text-gray-700 space-y-2">
                <li><strong>Access:</strong> Request access to your personal information</li>
                <li><strong>Correction:</strong> Request correction of inaccurate information</li>
                <li><strong>Deletion:</strong> Request deletion of your personal information</li>
                <li><strong>Portability:</strong> Request a copy of your data in a portable format</li>
                <li><strong>Opt-out:</strong> Opt out of marketing communications</li>
              </ul>
              <p className="text-gray-700 mt-3">
                To exercise these rights, please contact us at the information provided below.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">7. Data Security</h2>
              <p className="text-gray-700 mb-3">
                We implement appropriate technical and organizational measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction. However, no method of transmission over the internet or electronic storage is 100% secure.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">8. Children's Privacy</h2>
              <p className="text-gray-700">
                Our service is not intended for children under 13 years of age. We do not knowingly collect personal information from children under 13. If you believe we have collected information from a child under 13, please contact us immediately.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">9. Changes to This Privacy Policy</h2>
              <p className="text-gray-700">
                We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date. Your continued use of our service after any modifications constitutes acceptance of the updated Privacy Policy.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">10. Contact Information</h2>
              <p className="text-gray-700 mb-3">
                If you have any questions about this Privacy Policy or our privacy practices, please contact us:
              </p>
              <div className="bg-gray-50 p-4 rounded-lg">
                <p className="text-gray-700">
                  <strong>Email:</strong> privacy@aimeetingsummarizer.com<br />
                  <strong>Company:</strong> Fintech Digital<br />
                  <strong>Address:</strong> Sri Lanka
                </p>
              </div>
            </section>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-white border-t mt-12">
        <div className="container mx-auto px-4 py-8">
          <div className="text-center text-gray-500">
            <p>&copy; 2025 all rights reserved Fintech Digital.</p>
            <div className="mt-4 space-x-6">
              <a href="/privacy-policy" className="text-primary-600 hover:text-primary-700">Privacy Policy</a>
              <a href="/refund-policy" className="text-primary-600 hover:text-primary-700">Refund Policy</a>
              <a href="/terms" className="text-primary-600 hover:text-primary-700">Terms & Conditions</a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}
